//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18408.
// 
#pragma warning disable 1591

namespace Element.Sigma.Web.Biz.P6WS.AuthenticationService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AuthenticationServiceSOAP12Binding", Namespace="http://ws.primavera.com/2008/p6/6.2/Authentication")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IntegrationFaultType))]
    public partial class AuthenticationService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback LogoutOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadDatabaseInstancesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadSessionPropertiesOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateSessionPropertiesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AuthenticationService() {
            this.Url = global::Element.Sigma.Web.Biz.Properties.Settings.Default.Element_Sigma_Web_Biz_P6WS_AuthenticationService_AuthenticationService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event LogoutCompletedEventHandler LogoutCompleted;
        
        /// <remarks/>
        public event ReadDatabaseInstancesCompletedEventHandler ReadDatabaseInstancesCompleted;
        
        /// <remarks/>
        public event ReadSessionPropertiesCompletedEventHandler ReadSessionPropertiesCompleted;
        
        /// <remarks/>
        public event UpdateSessionPropertiesCompletedEventHandler UpdateSessionPropertiesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:Login", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("LoginResponse", Namespace="http://ws.primavera.com/2008/p6/6.2/Authentication")]
        public LoginResponse Login([System.Xml.Serialization.XmlElementAttribute("Login", Namespace="http://ws.primavera.com/2008/p6/6.2/Authentication")] Login Login1) {
            object[] results = this.Invoke("Login", new object[] {
                        Login1});
            return ((LoginResponse)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(Login Login1) {
            this.LoginAsync(Login1, null);
        }
        
        /// <remarks/>
        public void LoginAsync(Login Login1, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        Login1}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:Logout", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("LogoutResponse", Namespace="http://ws.primavera.com/2008/p6/6.2/Authentication")]
        public LogoutResponse Logout([System.Xml.Serialization.XmlElementAttribute("Logout", Namespace="http://ws.primavera.com/2008/p6/6.2/Authentication")] object Logout1) {
            object[] results = this.Invoke("Logout", new object[] {
                        Logout1});
            return ((LogoutResponse)(results[0]));
        }
        
        /// <remarks/>
        public void LogoutAsync(object Logout1) {
            this.LogoutAsync(Logout1, null);
        }
        
        /// <remarks/>
        public void LogoutAsync(object Logout1, object userState) {
            if ((this.LogoutOperationCompleted == null)) {
                this.LogoutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogoutOperationCompleted);
            }
            this.InvokeAsync("Logout", new object[] {
                        Logout1}, this.LogoutOperationCompleted, userState);
        }
        
        private void OnLogoutOperationCompleted(object arg) {
            if ((this.LogoutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogoutCompleted(this, new LogoutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:ReadDatabaseInstances", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ReadDatabaseInstancesResponse", Namespace="http://ws.primavera.com/2008/p6/6.2/Authentication")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("DatabaseInstance", IsNullable=false)]
        public ReadDatabaseInstancesResponseDatabaseInstance[] ReadDatabaseInstances([System.Xml.Serialization.XmlElementAttribute("ReadDatabaseInstances", Namespace="http://ws.primavera.com/2008/p6/6.2/Authentication")] object ReadDatabaseInstances1) {
            object[] results = this.Invoke("ReadDatabaseInstances", new object[] {
                        ReadDatabaseInstances1});
            return ((ReadDatabaseInstancesResponseDatabaseInstance[])(results[0]));
        }
        
        /// <remarks/>
        public void ReadDatabaseInstancesAsync(object ReadDatabaseInstances1) {
            this.ReadDatabaseInstancesAsync(ReadDatabaseInstances1, null);
        }
        
        /// <remarks/>
        public void ReadDatabaseInstancesAsync(object ReadDatabaseInstances1, object userState) {
            if ((this.ReadDatabaseInstancesOperationCompleted == null)) {
                this.ReadDatabaseInstancesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadDatabaseInstancesOperationCompleted);
            }
            this.InvokeAsync("ReadDatabaseInstances", new object[] {
                        ReadDatabaseInstances1}, this.ReadDatabaseInstancesOperationCompleted, userState);
        }
        
        private void OnReadDatabaseInstancesOperationCompleted(object arg) {
            if ((this.ReadDatabaseInstancesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadDatabaseInstancesCompleted(this, new ReadDatabaseInstancesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:ReadSessionProperties", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ReadSessionPropertiesResponse", Namespace="http://ws.primavera.com/2008/p6/6.2/Authentication")]
        public ReadSessionPropertiesResponse ReadSessionProperties([System.Xml.Serialization.XmlElementAttribute("ReadSessionProperties", Namespace="http://ws.primavera.com/2008/p6/6.2/Authentication")] object ReadSessionProperties1) {
            object[] results = this.Invoke("ReadSessionProperties", new object[] {
                        ReadSessionProperties1});
            return ((ReadSessionPropertiesResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ReadSessionPropertiesAsync(object ReadSessionProperties1) {
            this.ReadSessionPropertiesAsync(ReadSessionProperties1, null);
        }
        
        /// <remarks/>
        public void ReadSessionPropertiesAsync(object ReadSessionProperties1, object userState) {
            if ((this.ReadSessionPropertiesOperationCompleted == null)) {
                this.ReadSessionPropertiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadSessionPropertiesOperationCompleted);
            }
            this.InvokeAsync("ReadSessionProperties", new object[] {
                        ReadSessionProperties1}, this.ReadSessionPropertiesOperationCompleted, userState);
        }
        
        private void OnReadSessionPropertiesOperationCompleted(object arg) {
            if ((this.ReadSessionPropertiesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadSessionPropertiesCompleted(this, new ReadSessionPropertiesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:UpdateSessionProperties", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("UpdateSessionPropertiesResponse", Namespace="http://ws.primavera.com/2008/p6/6.2/Authentication")]
        public UpdateSessionPropertiesResponse UpdateSessionProperties([System.Xml.Serialization.XmlElementAttribute("UpdateSessionProperties", Namespace="http://ws.primavera.com/2008/p6/6.2/Authentication")] UpdateSessionProperties UpdateSessionProperties1) {
            object[] results = this.Invoke("UpdateSessionProperties", new object[] {
                        UpdateSessionProperties1});
            return ((UpdateSessionPropertiesResponse)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateSessionPropertiesAsync(UpdateSessionProperties UpdateSessionProperties1) {
            this.UpdateSessionPropertiesAsync(UpdateSessionProperties1, null);
        }
        
        /// <remarks/>
        public void UpdateSessionPropertiesAsync(UpdateSessionProperties UpdateSessionProperties1, object userState) {
            if ((this.UpdateSessionPropertiesOperationCompleted == null)) {
                this.UpdateSessionPropertiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateSessionPropertiesOperationCompleted);
            }
            this.InvokeAsync("UpdateSessionProperties", new object[] {
                        UpdateSessionProperties1}, this.UpdateSessionPropertiesOperationCompleted, userState);
        }
        
        private void OnUpdateSessionPropertiesOperationCompleted(object arg) {
            if ((this.UpdateSessionPropertiesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateSessionPropertiesCompleted(this, new UpdateSessionPropertiesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.primavera.com/2008/p6/6.2/Authentication")]
    public partial class Login {
        
        private string userNameField;
        
        private string passwordField;
        
        private int databaseInstanceIdField;
        
        private bool databaseInstanceIdFieldSpecified;
        
        private bool verboseFaultsField;
        
        private bool verboseFaultsFieldSpecified;
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public int DatabaseInstanceId {
            get {
                return this.databaseInstanceIdField;
            }
            set {
                this.databaseInstanceIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DatabaseInstanceIdSpecified {
            get {
                return this.databaseInstanceIdFieldSpecified;
            }
            set {
                this.databaseInstanceIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool VerboseFaults {
            get {
                return this.verboseFaultsField;
            }
            set {
                this.verboseFaultsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VerboseFaultsSpecified {
            get {
                return this.verboseFaultsFieldSpecified;
            }
            set {
                this.verboseFaultsFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.primavera.com/2008/p6/6.2/IntegrationFaultType")]
    public partial class IntegrationFaultType {
        
        private IntegrationFaultCodeType errorTypeField;
        
        private int errorCodeField;
        
        private string errorDescriptionField;
        
        private string stackTraceField;
        
        /// <remarks/>
        public IntegrationFaultCodeType ErrorType {
            get {
                return this.errorTypeField;
            }
            set {
                this.errorTypeField = value;
            }
        }
        
        /// <remarks/>
        public int ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string StackTrace {
            get {
                return this.stackTraceField;
            }
            set {
                this.stackTraceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.primavera.com/2008/p6/6.2/IntegrationFaultType")]
    public enum IntegrationFaultCodeType {
        
        /// <remarks/>
        General,
        
        /// <remarks/>
        Presentation,
        
        /// <remarks/>
        Network,
        
        /// <remarks/>
        Server,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Business Rules")]
        BusinessRules,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.primavera.com/2008/p6/6.2/Authentication")]
    public partial class LoginResponse {
        
        private bool returnField;
        
        private bool returnFieldSpecified;
        
        /// <remarks/>
        public bool Return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReturnSpecified {
            get {
                return this.returnFieldSpecified;
            }
            set {
                this.returnFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.primavera.com/2008/p6/6.2/Authentication")]
    public partial class LogoutResponse {
        
        private bool returnField;
        
        private bool returnFieldSpecified;
        
        /// <remarks/>
        public bool Return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReturnSpecified {
            get {
                return this.returnFieldSpecified;
            }
            set {
                this.returnFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.primavera.com/2008/p6/6.2/Authentication")]
    public partial class ReadDatabaseInstancesResponseDatabaseInstance {
        
        private int databaseInstanceIdField;
        
        private string databaseEncodingField;
        
        private string databaseNameField;
        
        private DatabaseTypeType databaseTypeField;
        
        private string databaseUrlField;
        
        /// <remarks/>
        public int DatabaseInstanceId {
            get {
                return this.databaseInstanceIdField;
            }
            set {
                this.databaseInstanceIdField = value;
            }
        }
        
        /// <remarks/>
        public string DatabaseEncoding {
            get {
                return this.databaseEncodingField;
            }
            set {
                this.databaseEncodingField = value;
            }
        }
        
        /// <remarks/>
        public string DatabaseName {
            get {
                return this.databaseNameField;
            }
            set {
                this.databaseNameField = value;
            }
        }
        
        /// <remarks/>
        public DatabaseTypeType DatabaseType {
            get {
                return this.databaseTypeField;
            }
            set {
                this.databaseTypeField = value;
            }
        }
        
        /// <remarks/>
        public string DatabaseUrl {
            get {
                return this.databaseUrlField;
            }
            set {
                this.databaseUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.primavera.com/2008/p6/6.2/Authentication")]
    public enum DatabaseTypeType {
        
        /// <remarks/>
        Oracle,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("SQL Server")]
        SQLServer,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.primavera.com/2008/p6/6.2/Authentication")]
    public partial class ReadSessionPropertiesResponse {
        
        private bool isValidField;
        
        private int userObjectIdField;
        
        private string userNameField;
        
        private int databaseInstanceIdField;
        
        private string databaseEncodingField;
        
        private string databaseNameField;
        
        private DatabaseTypeType databaseTypeField;
        
        private string databaseUrlField;
        
        private bool ignoreNullComplexFieldsField;
        
        private bool verboseFaultsField;
        
        /// <remarks/>
        public bool IsValid {
            get {
                return this.isValidField;
            }
            set {
                this.isValidField = value;
            }
        }
        
        /// <remarks/>
        public int UserObjectId {
            get {
                return this.userObjectIdField;
            }
            set {
                this.userObjectIdField = value;
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public int DatabaseInstanceId {
            get {
                return this.databaseInstanceIdField;
            }
            set {
                this.databaseInstanceIdField = value;
            }
        }
        
        /// <remarks/>
        public string DatabaseEncoding {
            get {
                return this.databaseEncodingField;
            }
            set {
                this.databaseEncodingField = value;
            }
        }
        
        /// <remarks/>
        public string DatabaseName {
            get {
                return this.databaseNameField;
            }
            set {
                this.databaseNameField = value;
            }
        }
        
        /// <remarks/>
        public DatabaseTypeType DatabaseType {
            get {
                return this.databaseTypeField;
            }
            set {
                this.databaseTypeField = value;
            }
        }
        
        /// <remarks/>
        public string DatabaseUrl {
            get {
                return this.databaseUrlField;
            }
            set {
                this.databaseUrlField = value;
            }
        }
        
        /// <remarks/>
        public bool IgnoreNullComplexFields {
            get {
                return this.ignoreNullComplexFieldsField;
            }
            set {
                this.ignoreNullComplexFieldsField = value;
            }
        }
        
        /// <remarks/>
        public bool VerboseFaults {
            get {
                return this.verboseFaultsField;
            }
            set {
                this.verboseFaultsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.primavera.com/2008/p6/6.2/Authentication")]
    public partial class UpdateSessionProperties {
        
        private bool ignoreNullComplexFieldsField;
        
        private bool ignoreNullComplexFieldsFieldSpecified;
        
        private bool verboseFaultsField;
        
        private bool verboseFaultsFieldSpecified;
        
        /// <remarks/>
        public bool IgnoreNullComplexFields {
            get {
                return this.ignoreNullComplexFieldsField;
            }
            set {
                this.ignoreNullComplexFieldsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IgnoreNullComplexFieldsSpecified {
            get {
                return this.ignoreNullComplexFieldsFieldSpecified;
            }
            set {
                this.ignoreNullComplexFieldsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool VerboseFaults {
            get {
                return this.verboseFaultsField;
            }
            set {
                this.verboseFaultsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VerboseFaultsSpecified {
            get {
                return this.verboseFaultsFieldSpecified;
            }
            set {
                this.verboseFaultsFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.primavera.com/2008/p6/6.2/Authentication")]
    public partial class UpdateSessionPropertiesResponse {
        
        private bool returnField;
        
        private bool returnFieldSpecified;
        
        /// <remarks/>
        public bool Return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReturnSpecified {
            get {
                return this.returnFieldSpecified;
            }
            set {
                this.returnFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LoginResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LoginResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void LogoutCompletedEventHandler(object sender, LogoutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LogoutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LogoutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LogoutResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LogoutResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ReadDatabaseInstancesCompletedEventHandler(object sender, ReadDatabaseInstancesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadDatabaseInstancesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadDatabaseInstancesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReadDatabaseInstancesResponseDatabaseInstance[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReadDatabaseInstancesResponseDatabaseInstance[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ReadSessionPropertiesCompletedEventHandler(object sender, ReadSessionPropertiesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadSessionPropertiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadSessionPropertiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReadSessionPropertiesResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReadSessionPropertiesResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void UpdateSessionPropertiesCompletedEventHandler(object sender, UpdateSessionPropertiesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateSessionPropertiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateSessionPropertiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UpdateSessionPropertiesResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UpdateSessionPropertiesResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591