//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Element.Sigma.Web.Biz.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.101.107:8091/p6ws/services/ActivityStepTemplateService")]
        public string Element_Sigma_Web_Biz_P6WS_ActivityService_ActivityStepTemplateService {
            get {
                return ((string)(this["Element_Sigma_Web_Biz_P6WS_ActivityService_ActivityStepTemplateService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.101.107:8091/p6ws/services/AuthenticationService")]
        public string Element_Sigma_Web_Biz_P6WS_AuthenticationService_AuthenticationService {
            get {
                return ((string)(this["Element_Sigma_Web_Biz_P6WS_AuthenticationService_AuthenticationService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.101.107:8091/p6ws/services/ProjectDocumentService")]
        public string Element_Sigma_Web_Biz_P6WS_ProjectService_ProjectDocumentService {
            get {
                return ((string)(this["Element_Sigma_Web_Biz_P6WS_ProjectService_ProjectDocumentService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.101.107:8091/p6ws/services/ProjectDocumentService")]
        public string Element_Sigma_Web_Biz_P6WS_WBSService_ProjectDocumentService {
            get {
                return ((string)(this["Element_Sigma_Web_Biz_P6WS_WBSService_ProjectDocumentService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.101.107:8091/p6ws/services/GlobalPreferencesService")]
        public string Element_Sigma_Web_Biz_P6WS_CalendarService_GlobalPreferencesService {
            get {
                return ((string)(this["Element_Sigma_Web_Biz_P6WS_CalendarService_GlobalPreferencesService"]));
            }
        }
    }
}
